klientFiles = boubles_main.c close.c collisionHandler.c dropFunction.c initFunctions.c jump.c keyInput.c screenUpdater.c shoot.c sound.c tcp_socket.c
build : $(klientFiles)
	gcc $(klientFiles) -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_mixer -o bin/Debug/Bubbles.exe